### ISSUE TITLE
Mac test failures: RemoteTest

### ISSUE THREAD

**Issue by acruise** [reactors-io/reactors#59]
```
[info] RemoteTest:
[info] - UDP transport should send events correctly
[info] - UDP transport should send and receive events correctly *** FAILED ***
[info]   java.lang.Error: java.io.IOException: No such file or directory
[info]   at sun.nio.ch.DatagramSocketAdaptor.close(DatagramSocketAdaptor.java:352)
[info]   at io.reactors.remote.UdpTransport.shutdown(UdpTransport.scala:81)
[info]   at io.reactors.Remote$$anonfun$shutdown$2.apply(Remote.scala:31)
[info]   at io.reactors.Remote$$anonfun$shutdown$2.apply(Remote.scala:31)
[info]   at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
[info]   at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
[info]   at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
[info]   at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)
[info]   at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
[info]   at scala.collection.mutable.HashMap.foreach(HashMap.scala:99)
[info]   ...
[info]   Cause: java.io.IOException: No such file or directory
[info]   at sun.nio.ch.NativeThread.signal(Native Method)
[info]   at sun.nio.ch.DatagramChannelImpl.implCloseSelectableChannel(DatagramChannelImpl.java:1017)
[info]   at java.nio.channels.spi.AbstractSelectableChannel.implCloseChannel(AbstractSelectableChannel.java:234)
[info]   at java.nio.channels.spi.AbstractInterruptibleChannel.close(AbstractInterruptibleChannel.java:115)
[info]   at sun.nio.ch.DatagramSocketAdaptor.close(DatagramSocketAdaptor.java:350)
[info]   at io.reactors.remote.UdpTransport.shutdown(UdpTransport.scala:81)
[info]   at io.reactors.Remote$$anonfun$shutdown$2.apply(Remote.scala:31)
[info]   at io.reactors.Remote$$anonfun$shutdown$2.apply(Remote.scala:31)
[info]   at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
[info]   at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
[info]   ...
[info] ScalaTest
[info] Run completed in 1 second, 418 milliseconds.
[info] Total number of tests run: 2
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
[error] Failed: Total 2, Failed 1, Errors 0, Passed 1
[error] Failed tests:
[error]        	io.reactors.remote.RemoteTest
```

**Comment by acruise** [comment]
This is with sbt 0.13.9, launched with -Xmx4g, Java 1.8.0_112

**Comment by cantor-chron** [comment]
It seems like this is some OSX-specific behavior again. I'm thinking we should get a mac mini for our CI.

I will dig into this, but I'll have to get access to a Mac machine first.
