### ISSUE TITLE
Mac test failures: DebuggerTest

### ISSUE THREAD

**Issue by acruise** [reactors-io/reactors#60]
```
[info] DebuggerTest:
[info] - test basic debugger scenarios *** FAILED ***
[info]   java.io.IOException: Cannot run program "xvfb-run" (in directory ".."): error=2, No such file or directory
[info]   at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
[info]   at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:69)
[info]   at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:98)
[info]   at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang(ProcessBuilderImpl.scala:112)
[info]   at io.reactors.debugger.DebuggerTest$$anonfun$1.apply(debugger-tests.scala:23)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
[info]   ...
[info]   Cause: java.io.IOException: error=2, No such file or directory
[info]   at java.lang.UNIXProcess.forkAndExec(Native Method)
[info]   at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
[info]   at java.lang.ProcessImpl.start(ProcessImpl.java:134)
[info]   at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
[info]   at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:69)
[info]   at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:98)
[info]   at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang(ProcessBuilderImpl.scala:112)
[info]   at io.reactors.debugger.DebuggerTest$$anonfun$1.apply(debugger-tests.scala:23)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   ...
```

**Comment by acruise** [comment]
Xvfb happens to be installed on my mac (comes with XQuartz I guess), but not this 'xvfb-run' script that's typically found on Linux. I tried copying a version of xvfb-run from elsewhere but it failed with dependency problems, so I gave up.

**Comment by tiborlotz** [comment]
This should be fixed by the following commit:

https://github.com/reactors-io/reactors/commit/916a33d864eb1e40f58ce70355d1ed78b363c562
