### ISSUE TITLE
NullPointerException with union()

### ISSUE THREAD

**Issue by akarnokd** [reactors-io/reactors#64]
[My updated code](https://github.com/akarnokd/akarnokd-misc-scala/blob/master/src/main/scala/ScrabbleWithReactorsIO.scala#L196) throws a `NullPointerException` inside `Events`. L2820 contains the line `subscription.unsubscribe()`:

```
Exception in thread "main" java.lang.NullPointerException
	at io.reactors.Events$PostfixUnionNestedObserver.unreact(Events.scala:2820)
	at io.reactors.protocol.Conversions$ToEvents.onReaction(Conversions.scala:49)
	at io.reactors.Events$PostfixUnionObserver.react(Events.scala:2797)
	at io.reactors.Events$MapObserver.react(Events.scala:2215)
	at io.reactors.Events$ReducePastObserver.unreact(Events.scala:1722)
	at io.reactors.Events$FilterObserver.unreact(Events.scala:2157)
	at io.reactors.Events$FilterObserver.unreact(Events.scala:2157)
	at io.reactors.protocol.Conversions$ToEvents.onReaction(Conversions.scala:49)
	at io.reactors.Events$Filter.onReaction(Events.scala:2138)
	at io.reactors.Events$Filter.onReaction(Events.scala:2138)
	at io.reactors.Events$ReducePast.onReaction(Events.scala:1697)
	at io.reactors.Events$Map.onReaction(Events.scala:2197)
	at io.reactors.Events$PostfixUnion.onReaction(Events.scala:2766)
	at io.reactors.Events$Take.onReaction(Events.scala:2429)
	at io.reactors.Events$ReducePast.onReaction(Events.scala:1697)
	at io.reactors.Events$class.onEventOrDone(Events.scala:89)
	at io.reactors.Events$ReducePast.onEventOrDone(Events.scala:1688)
	at io.reactors.Events$class.onEvent(Events.scala:101)
	at io.reactors.Events$ReducePast.onEvent(Events.scala:1688)
	at ScrabbleWithReactorsIO$.first(ScrabbleWithReactorsIO.scala:212)
	at ScrabbleWithReactorsIO$.scrabble(ScrabbleWithReactorsIO.scala:184)
	at ScrabbleWithReactorsIO$.main(ScrabbleWithReactorsIO.scala:48)
	at ScrabbleWithReactorsIO.main(ScrabbleWithReactorsIO.scala)
```

This minimalist example also crashes with NPE:

```scala
import java.util

import io.reactors._
import io.reactors.protocol._

import scala.collection.JavaConverters._

object ReactorsIOUnion {

  def main(args: Array[String]): Unit = {
    util.Arrays.asList(1, 2, 3, 4, 5)
      .asScala
      .toEvents
      .map((v) => util.Arrays.asList(v, v + 1).asScala.toEvents)
      .union
      .onEvent(println)
  }
}
```

```
1
2
Exception in thread "main" java.lang.NullPointerException
	at io.reactors.Events$PostfixUnionObserver.unreact(Events.scala:2805)
	at io.reactors.Events$MapObserver.unreact(Events.scala:2221)
	at io.reactors.protocol.Conversions$ToEvents.onReaction(Conversions.scala:49)
	at io.reactors.Events$Map.onReaction(Events.scala:2197)
	at io.reactors.Events$PostfixUnion$mcI$sp.onReaction$mcI$sp(Events.scala:2766)
	at io.reactors.Events$PostfixUnion$mcI$sp.onReaction(Events.scala:2764)
	at io.reactors.Events$mcI$sp$class.onEventOrDone$mcI$sp(Events.scala:89)
	at io.reactors.Events$PostfixUnion$mcI$sp.onEventOrDone$mcI$sp(Events.scala:2760)
	at io.reactors.Events$mcI$sp$class.onEvent$mcI$sp(Events.scala:101)
	at io.reactors.Events$PostfixUnion$mcI$sp.onEvent$mcI$sp(Events.scala:2760)
	at ReactorsIOUnion$.main(ReactorsIOUnion.scala:21)
	at ReactorsIOUnion.main(ReactorsIOUnion.scala)
```

**Comment by axel22** [comment]
This is an unfortunate interaction with event streams that synchronously emit events, such as `toEvents` on collections. Most other event streams emit asynchronously, i.e. after `onEvent` returns.

It should be fixed now after this commit:

https://github.com/reactors-io/reactors/commit/1ba5836da590da0f96c5bee00d06288750b60bd9

I will release a new micro version to Sonatype.

**Comment by cantor-chron** [comment]
A snapshot release should already contain the patch.

**Comment by akarnokd** [comment]
Could you point me to the snapshot repo? [Sonatype](https://oss.sonatype.org/content/repositories/snapshots/io/reactors/) doesn't seem to contain anything.

**Comment by cantor-chron** [comment]
There was a glitch in the snapshot publishing pipeline. You should now be able to find the new snapshot here:

https://oss.sonatype.org/content/repositories/snapshots/io/reactors/reactors_2.11/

You should be able to depend on this version like this if you are using SBT:

```
resolvers ++= Seq(
  "Sonatype OSS Snapshots" at
    "https://oss.sonatype.org/content/repositories/snapshots",
  "Sonatype OSS Releases" at
    "https://oss.sonatype.org/content/repositories/releases"
)
libraryDependencies ++= Seq(
  "io.reactors" %% "reactors" % "0.9-SNAPSHOT")
```

**Comment by axel22** [comment]
Should be fixed now.
